name: Performance Tests

on:
  schedule:
    # Run performance tests weekly on Sundays at 3 AM UTC
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  performance:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Run Performance Tests
      run: npx playwright test --grep "@performance"
      env:
        CI: true
        HEADLESS: true
        
    - name: Generate Performance Report
      run: |
        echo "Performance test completed"
        # Add custom performance reporting logic here
        
    - name: Upload Performance Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: performance-results
        path: reports/
        retention-days: 90
        
    - name: Notify on Performance Issues
      if: failure()
      run: |
        if [ -n "${{ secrets.SLACK_WEBHOOK }}" ]; then
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "channel": "#performance-alerts",
            "text": "❌ Performance tests failed in ${{ github.repository }}",
            "attachments": [
              {
                "color": "danger",
                "fields": [
                  {
                    "title": "Branch",
                    "value": "${{ github.ref_name }}",
                    "short": true
                  },
                  {
                    "title": "Commit",
                    "value": "${{ github.sha }}",
                    "short": true
                  },
                  {
                    "title": "Build URL",
                    "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                    "short": false
                  }
                ]
              }
            ]
          }' \
          "${{ secrets.SLACK_WEBHOOK }}"
        else
          echo "SLACK_WEBHOOK secret not configured, skipping notification"
        fi
